# Generated by Django 4.1.2 on 2022-11-20 17:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_name_remove_user_surname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="requestcomment",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="requestcomment",
            old_name="request_id",
            new_name="request",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="admin_id",
            new_name="admin",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="ticketcomment",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="ticketcomment",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.AlterUniqueTogether(
            name="picture",
            unique_together={("ticket", "id")},
        ),
        migrations.AlterUniqueTogether(
            name="requestcomment",
            unique_together={("request", "id")},
        ),
        migrations.AlterUniqueTogether(
            name="ticketcomment",
            unique_together={("ticket", "id")},
        ),
        migrations.AddField(
            model_name="picture",
            name="url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="request",
            name="creation_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ticket",
            name="creation_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="request",
            name="state",
            field=models.CharField(
                choices=[(1, "submitted"), (2, "working on"), (3, "resolved")],
                default=1,
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="requestcomment",
            name="creation_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=models.CharField(
                choices=[(1, "submitted"), (2, "working on"), (3, "resolved")],
                default=1,
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="creation_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(
                max_length=256,
                validators=[django.core.validators.RegexValidator("^\\d+\\/?\\d*$")],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[django.core.validators.RegexValidator("^\\d{9}$")],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zipcode",
            field=models.CharField(
                max_length=6,
                validators=[django.core.validators.RegexValidator("^\\d{3} \\d{2}$")],
            ),
        ),
        migrations.RemoveField(
            model_name="picture",
            name="image",
        ),
    ]
