# Generated by Django 4.1.2 on 2022-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ticket_id_picture_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[(1, 'submitted'), (2, 'working on'), (3, 'resolved'), (4, 'denied')], default=1, max_length=256),
        ),
    ]
